### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by tt511327** [Pawl-Patrol/Dynamic-Voice-Channels#13]
Can the bot add a new setting : **set the default permission for the voice channel**
when I create a new voice channel, the bot can set the default permission for the voice channel

because now there is many bad bot sent the harassing messages
I want to set the default permission for every channel to let @everyone can't see
and some roles can see all channels
thank you

**Comment by tt511327** [comment]
@Pawl-Patrol

**Comment by Pawl-Patrol** [comment]
Sure. I will implement this. Due to Discord making message content unavailable in a few months, a rewrite has to be made anyways.

**Comment by Pawl-Patrol** [comment]
Permission overwrites are now copied from the originial channel. Use this channel to set your permissions :)

**Comment by tt511327** [comment]
Thank you.
I find a bug:
I could edit the channel that I created before.
But now, the permission of the channel copies from  the originial channel,
I don't have permission to edit the name / server / connection ...and others


the last, thank you again.

**Comment by Pawl-Patrol** [comment]
If you want users without any permissions to still edit their created channel, an server admin has to give these permissions in the channel overwrites of the originial channel. If it's much wanted, i can implement all edit commands again, but I found them to be redundant.

**Comment by tt511327** [comment]
I think the edit commands are unnecessary.
I mean the permission of new channel can copy the original channel, "and" add the permission for the creator.  Just like before 
so that user can use setting of DC to edit the channel
prevent them from editing the original channel

**Comment by Pawl-Patrol** [comment]
Thank you, I understand now what you meant. Completely forget to implement it. Give me half an hour and It'll be fixed. Update: Users will get manage_channel, move_members, connect, speak and view channel permissions for now. I have to make this configurable later on.
