### ISSUE TITLE
Change voice region / server / connection

### ISSUE THREAD

**Issue by AngDrew** [Pawl-Patrol/Dynamic-Voice-Channels#14]
is there any way to make it instead of making new channel with Automatic region to specific region like Singapora / Hongkong / Japan / etc..
because the discord bandwidth seems overloaded in singapore server..

**Comment by Pawl-Patrol** [comment]
Thank you for the suggestion. Bot will be updated soon. In the newer version settings like region and video quality are copied from the original channel.
