### ISSUE TITLE
Bot does nothing after a few hours

### ISSUE THREAD

**Issue by deRaidA** [Pawl-Patrol/Dynamic-Voice-Channels#15]
So, I installed your bot and it was working fine for the first few hours.
But now it is still online on the right, but does nothing with the dvc!... commands.
Is there a known problem at the moment, or are you updating to "/" commands at the moment?

![image](https://user-images.githubusercontent.com/52463719/149405994-42497550-bcb1-49be-93f7-0bccd93618a0.png)

**Comment by deRaidA** [comment]
by the way. Really cool and simple bot (when it works :D).

**Comment by deRaidA** [comment]
Works fine now. Looks life you updatet to "/" commands.
Really nice plugin

**Comment by Pawl-Patrol** [comment]
Thank you :) It took a little while to completely move from prefix commands to slash commands and I am very glad that it works.
