### ISSUE TITLE
Can't change prefix

### ISSUE THREAD

**Issue by shuwarida** [Pawl-Patrol/Dynamic-Voice-Channels#2]
![image](https://user-images.githubusercontent.com/1415166/94249971-6ecbdd00-ff42-11ea-9722-b5b05a51bab1.png)

**Comment by Pawl-Patrol** [comment]
If you change the prefix to "dc" the command to change it back would be "dcprefix dvc!". The right way to assign the prefix you wanted would be "dvc!prefix dc!".
