### ISSUE TITLE
Intents error modul

### ISSUE THREAD

**Issue by pampampam999** [Pawl-Patrol/Dynamic-Voice-Channels#3]
in this time i had clone this code and run , in my package error in discord.ext impor menus and inten=discord.Intent.all() . i don't no why because iam so beginer i this case

**Comment by Pawl-Patrol** [comment]
Make sure to update your discord.py library to the latest version (1.5+) and intall the unofficial library for menus (https://github.com/Rapptz/discord-ext-menus). This should fix the errors.

**Comment by alrakaa** [comment]
i found error 
 File "bot.py", line 209, in <module>
    Bot().run(config.token)
  File "bot.py", line 48, in __init__

can help me, im done use discord.py ver 1.5.1

**Comment by Pawl-Patrol** [comment]
Did you put your bot's token in the config.py file? I can't really find an error here.

**Comment by alrakaa** [comment]
yes done, but still error

**Comment by Pawl-Patrol** [comment]
Can you give me the complete traceback of the error?

**Comment by alrakaa** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\alanw\Desktop\Dynamic-Voice-Channels-master> py bot.py
Traceback (most recent call last):
  File "bot.py", line 1, in <module>
    import discord
  File "C:\Users\alanw\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\alanw\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Users\alanw\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Users\alanw\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax
PS C:\Users\alanw\Desktop\Dynamic-Voice-Channels-master>

**Comment by alrakaa** [comment]
Traceback (most recent call last):
  File "bot.py", line 209, in <module>
    Bot().run(config.token)
  File "bot.py", line 48, in __init__
    self.load_extension(extension)
  File "C:\Users\alanw\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\bot.py", line 664, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\alanw\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\bot.py", line 610, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.settings' raised an error: ImportError: cannot import name 'cached_property' from 'functools' (C:\Users\alanw\AppData\Local\Programs\Python\Python37\lib\functools.py)

**Comment by AlikaIntan** [comment]
me too

**Comment by Pawl-Patrol** [comment]
There seems to be something wrong with your versions. I'm using Python 3.8, maybe that's the problem.

**Comment by Mine0408** [comment]
If I turn off the bot and turn it on again, will the automatic channel disappear?

**Comment by Pawl-Patrol** [comment]
No. Channels are saved inside a json file and loaded upon start.

**Comment by Mine0408** [comment]
> 不會。頻道會保存在json文件中，並在啟動時加載。

Do you mean jsonfile.py?  Because when I turned on the bot just now, the automatic channel was invalid

**Comment by Mine0408** [comment]
> No. Channels are saved inside a json file and loaded upon start.

Do you mean jsonfile.py?  Because when I turned on the robot just now, the automatic channel was invalid

**Comment by Mine0408** [comment]
I have a problem 
FileNotFoundError: [Errno 2] No such file or directory: 'data/configs.json-52539530-dd1a-4192-be8e-e7f10d1bea73.tmp'
I created a file called configs.json, but it shows this string of characters

**Comment by Pawl-Patrol** [comment]
Do you have a folder called "data" in your root directory? Usually it should create the configs.json file by itself. It creates a temporary file with a unique name and then atomically replaces the old file. This is why you see this string of characters.
