### ISSUE TITLE
Public Bot Instance needs to pass Verification

### ISSUE THREAD

**Issue by ellisgeek** [Pawl-Patrol/Dynamic-Voice-Channels#5]
I was planning on testing the bot in one of my servers but it looks like it needs to pass Verification before it can be used in more servers.

https://support.discord.com/hc/en-us/articles/360040720412-Bot-Verification-and-Data-Whitelisting

**Comment by Pawl-Patrol** [comment]
Yes, I am aware of that. Just clone it for now.

**Comment by abrahammurciano** [comment]
Is this going to be fixed at some point in the near future? I've tried a few other similar bots, but none are as quick, good, and reliable as yours. I'd like to add this to more of my servers, but I was only able to add it to one before it reached the 100 server limit.

**Comment by Pawl-Patrol** [comment]
I've kicked the bot from some only-one-person servers and am working on the verification. (Had some problems with my identity verification). Thank you for the feedback, I really appreciate it. As long as the bot is small, I could easily host another instance of it on the vps, if you want so. Sorry for the circumstances.
